Repository brain-image-library/py-brain-inventory, pull requests merged in 2023-07, with the labels that each got.

#22 Update AUTHORS file
  AUTHORS
Labels: documentation

#29 Update get.py
  braininventory/get.py
Labels: enhancement, help wanted, CS Scholars

#18 Update get.py
  braininventory/get.py
Labels: enhancement, SAMS

#13 Update get.py
  braininventory/__init__.py
  braininventory/get.py
Labels: enhancement, SAMS

#15 Update setup.py
  braininventory/get.py
Labels: enhancement, SAMS

#34 Update get.py
  braininventory/get.py
Labels: enhancement, CS Scholars

#36 Update get.py
  braininventory/get.py
Labels: enhancement, CS Scholars

#49 Refactor code for improved readability and maintainability.
  README.md
  images/banner.jpg
Labels: documentation, enhancement

#38 Update get.py
  braininventory/get.py
Labels: enhancement, SAMS

#70 Added LICENSE
  LICENSE
Labels: enhancement, help wanted, SAMS

#37 27 frequency of affiliation
  braininventory/get.py
Labels: enhancement, CS Scholars

#19 Update get.py
  braininventory/get.py
Labels: enhancement, SAMS

#46 #45 get jsonfile
  braininventory/get.py
Labels: documentation, enhancement, CS Scholars

#44 Update get.py
  braininventory/get.py
Labels: enhancement, SAMS

#62 General Modality Tree Map: Update
  braininventory/get.py
Labels: documentation, enhancement, CS Scholars

#77 Update get.py
  braininventory/get.py
Labels: enhancement, good first issue, SAMS

#79 Update get.py
  braininventory/get.py
Labels: enhancement

#81 80 document method get random sample using chatgpt
  braininventory/get.py
Labels: documentation, SAMS

#83 82 write docstrings using chatgpt for all the functions without documentation
  braininventory/get.py
Labels: documentation, SAMS

#60 General Modality Bar Graph
  braininventory/get.py
Labels: documentation, enhancement, CS Scholars

#32 Update get.py
  braininventory/get.py
Labels: enhancement, help wanted, CS Scholars

#33 New metric request - get json file #25
  braininventory/get.py
Labels: enhancement, CS Scholars

#57 Update README.md
  README.md
Labels: SAMS

#68 Genotype Tree Map
  braininventory/get.py
  setup.py
Labels: enhancement, CS Scholars

#47 46 - get_date update
  braininventory/get.py
Labels: documentation, enhancement, CS Scholars

#39 Update get.py
  braininventory/get.py
Labels: enhancement, SAMS

#91 Fix issue with key
  braininventory/get.py
Labels: bug, CS Scholars

#87 Update get.py
  braininventory/get.py
Labels: enhancement, SAMS

#73 Add __get_similar_columns
  braininventory/get.py
Labels: enhancement, CS Scholars
